### ISSUE TITLE
k center resolver

### ISSUE THREAD

**Issue by heurainbow** [Doc-Zegno/ActiveLearningNLP#1]
Is this repo inspired by "Active Learning for Convolutional Neural Networks: A Core-Set Approach"?
If so, what's the difference of this robust k center resolver and that using gurobi in https://github.com/ozansener/active_learning_coreset

**Comment by Doc-Zegno** [comment]
You’re absolutely right, this project was inspired primarily by the mentioned article.
A robustness of solution, however, is achieved using algorithms and techniques covered in https://www.cs.umd.edu/sites/default/files/scholarly_papers/Rachel_Schwartz_1.pdf (that can be considered another greedy algorithm for improving the solution obtained by the original greedy one) rather than solving a mixed integer program with Gurobi.

Unfortunately, since this repository uses an almost pure Python implementation of such algorithms, the overall performance is not satisfactory at all. That’s why it’s not recommended to use it in “serious” projects

**Comment by heurainbow** [comment]
Thanks.
